In [2]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Using Vectorization: " + str((toc - tic) * 1000) + "ms")

print("==========================")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
    
toc = time.time()
print(c)
print("Using For Loop: " + str((toc - tic) * 1000) + "ms")



250059.54388516812
Using Vectorization: 1.8298625946ms
250059.54388517124
Using For Loop: 431.594133377ms


In [3]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(np.shape(c))
print(c)

(3, 3)
[[-0.25984661 -0.36588205 -0.13105908]
 [ 0.38436822  1.06641882  0.88507126]
 [-0.8888232  -1.42784764 -1.37503303]]


In [4]:
import numpy as np  
x = np.arange(9).reshape(1,3,3) 

print 'Array X:' 
print x 
print '\n'  
y = np.squeeze(x) 

print 'Array Y:' 
print y 
print '\n'  

print 'The shapes of X and Y array:' 
print x.shape, y.shape


Array X:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


Array Y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


The shapes of X and Y array:
(1, 3, 3) (3, 3)


In [6]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(np.shape(B))

(4, 1)


In [9]:
a = 0.6930587610394646
assert(isinstance(a, float))
print(isinstance(a, float))

True


In [28]:
a = np.arange(1, 5).reshape(4,1)
print(a)
print(a.shape)
print("   ")

b = np.arange(7, 9).reshape(1, 2)
print(b)
print(b.shape)
print("   ")

c = np.outer(a, b)
print(c)
print(c.shape)
print("   ")

d = np.dot(a, b.T)
print(d)
print(d.shape)
print("   ")


[[1]
 [2]
 [3]
 [4]]
(4, 1)
   
[[7 8]]
(1, 2)
   
[[ 7  8]
 [14 16]
 [21 24]
 [28 32]]
(4, 2)
   


ValueError: shapes (4,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)